apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: jkscpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jkscpipelinesjavascriptdocker 
    spec:
      containers:
        - name: jkscpipelinesjavascriptdocker 
          image: jks05ccontainerregistry.azurecr.io/jkscpipelinesjavascriptdocker 
          ports:
          - containerPort: 8080